spring:
  datasource:
    url: jdbc:mysql://192.168.119.130:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  data:
    elasticsearch:
      cluster-nodes: 192.168.119.130:9300
      cluster-name: elasticsearch
  elasticsearch:
    rest:
      uris: http://192.168.119.130:9200
logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.macro.mall: debug